utilizando spring security, documentando api com swagger e paginas jsp
analuijesus/vaasschool pull request #10
Opened 2022-02-15 13:24 UTC by analuijesus

2022-02-17 12:45 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/controller/LoginController.java
> +        return "login";
Só uma frescurinha mas esse login poderia estar dentro de uma pasta pra não ficar solto no WEB-INF

2022-02-17 12:45 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/controller/dto/CategoryLoginDto.java
> +    private String name;
Porque não deixar todos esses atributos como final?

2022-02-17 12:45 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/controller/dto/SubcategoryLoginDto.java
> +    private String code;
Porque não deixar final?

2022-02-17 12:45 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/controller/form/CourseForm.java
> +
[minor] - já que pulou linha aqui acho melhor pular entre todos ou somente apagar essa linha que sobrou....

2022-02-17 12:45 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/controller/form/SubcategoryForm.java
>  public class SubcategoryForm {
Repito o mesmo comentário para essa classe vi que em alguns momentos você acaba dando quebra de linha e em outros não....Padrão é bem importante (eu prefiro pular que acho que dá uma leitura melhor) mas isso é bem de gosto

2022-02-17 12:45 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/model/Category.java
> +    public void update(CategoryForm categoryForm) {
Legal!!

2022-02-17 12:45 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/security/AuthenticationService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("Error"));
Ana achei que acabou ficando muito genérica essa mensagem....oque você acha? É que error pode indicar qualquer tipo de erro....poderia ser algo como:  user `nome do user` not found, oque acha?

2022-02-17 12:45 UTC, mariasantosdev commented on src/main/webapp/WEB-INF/views/dashboard.jsp
> -</head>
apagou sem querer? parece que agora essa tag está sem fechamento

2022-02-17 15:26 UTC, thaisandre commented on src/main/java/br/com/vaasschool/controller/CourseController.java
> +        model.addAttribute("subcategories", subcategories);
apenas sugestão: aqui você poderia criar uma classe `CourseFormView` com todos estes objetos que são enviados para a view. é substituir estas 4 chamadas por apenas uma, como:

` model.addAttribute("courseFormView", new CourseFormView(category, subcategory, subcategories));`

isso evita passar entidades inteiras para view sem necessiadade também, e apenas disponibilizar o que ela realmente precisa.

2022-02-17 15:59 UTC, analuijesus commented on src/main/java/br/com/vaasschool/controller/api/CategoryApiController.java
> +    @GetMapping(path = "/api/categories", produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
Eu estava fazendo os testes no Postman, e por lá dava certo. Fui testar no navegador, realmente deu ruim do jeito que tava /;. Vou pesquisar sobre também.

2022-02-17 16:38 UTC, thaisandre requested changes

2022-02-17 18:10 UTC, analuijesus commented on src/main/java/br/com/vaasschool/controller/api/CategoryApiController.java
> +    @GetMapping(path = "/api/categories", produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
De qualquer forma, irei fazer a alteração. Mais pra frente eu quero voltar nisso.

2022-02-17 19:59 UTC, analuijesus commented on src/main/java/br/com/vaasschool/model/Question.java
>      @Enumerated(EnumType.STRING)
Conforme falamos, decidimos retirar o  @Enumerated(EnumType.STRING) :)

2022-02-17 20:00 UTC, analuijesus commented on src/main/java/br/com/vaasschool/controller/CourseController.java
> +        model.addAttribute("subcategories", subcategories);
Com toda certeza irei seguir desta forma. Vou utilizar esse projeto para continuar os estudos. Adorei a ideia/sugestão

2022-02-20 21:29 UTC, thaisandre commented on src/main/java/br/com/vaasschool/controller/api/CategoryApiController.java
> +    @GetMapping(path = "/api/categories", produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
boa!

2022-02-20 21:37 UTC, thaisandre approved these changes

2022-02-20 21:37 UTC, thaisandre commented on src/main/java/br/com/vaasschool/controller/form/SubcategoryForm.java
> +        return new Subcategory(name, code, description, explanatoryGuide, active, order, category);
boa! o construtor de `SubCategoryForm` poderia receber uma `Subcategory` direto - como você fez no `CategoryForm` também. apenas sugestão, vou aprovar para não atrasar a próxima semana

2022-02-20 21:38 UTC, thaisandre commented
parabéns, Ana! Ficou muito bom! :)

2022-02-21 12:41 UTC, mariasantosdev approved these changes

2022-02-21 13:23 UTC, merged