Semana2
analuijesus/vaasschool pull request #2
Opened 2021-11-12 21:12 UTC by analuijesus

2021-11-16 13:34 UTC, hopesoh commented on src/br/com/vaasschool/model/CourseVisibility.java
> +                .filter(cv -> cv.getDisplayName().equalsIgnoreCase(value))
Dá pra encapsular essa lógica lá no `CourseVisiability` e fazer algo como um `cv.is(value)`. Daí, lá dentro, a gente chama esse` getDisplayName().equalsIgnoreCase(value)`. É só uma dica, mas não precisa mudar não. :))

2021-11-16 13:37 UTC, hopesoh approved these changes

2021-11-17 18:29 UTC, mariasantosdev commented on src/br/com/vaasschool/model/validation/Validator.java
> +import java.util.regex.Pattern;
Esse import aqui sobrou?

2021-11-17 19:04 UTC, mariasantosdev approved these changes

2021-11-17 19:04 UTC, mariasantosdev commented on src/br/com/vaasschool/test/HtmlFileCreationTest.java
> +        CategoryReader categoryReader = new CategoryReader();
Poderiamos colocar dentro de um método essa parte...sendo dessa linha 18 até a 44, poderia se chamar `loadData` por exemplo

2021-11-17 19:04 UTC, mariasantosdev commented on src/br/com/vaasschool/test/SectionTest.java
> -//        s2.setOrder(2);
Podemos deletar esses códigos comentados né? Não temos mais setters na Section

2021-11-17 23:49 UTC, analuijesus commented on src/br/com/vaasschool/model/validation/Validator.java
> +import java.util.regex.Pattern;
sim ;/
retirados :)

2021-11-18 20:11 UTC, alexandreaquiles requested changes
Alguns comentários e sugestões de mudança!

2021-11-18 20:11 UTC, alexandreaquiles commented on src/br/com/vaasschool/test/CategoryHtmlPageGenerator.java
> +                    ps.println("<td>" + sub.getCourseNameList() + "<td>");
Aqui, poderia não precisa do `<td>`. Se deixarmos, ficaria 3 novos `<tds>` para cada subcategoria. Aí fica confuso. A ideia é apenas concatenar os dados mesmo.

2021-11-18 20:11 UTC, alexandreaquiles commented on src/br/com/vaasschool/test/CategoryHtmlPageGenerator.java
> +                    ps.println("<td>" + sub.getCourseNameList() + "<td>");
Talvez criar uma tabela dentro da tabela. Mas poderia ser apenas umas `<div>` mesmo, sabe?

2021-11-18 20:11 UTC, alexandreaquiles commented on src/br/com/vaasschool/test/CategoryHtmlPageGenerator.java
> +                ps.println("<td>" + c.getActive() + "<td>");
No card, não estava falando pra mostrar se está ativo ou não!

```suggestion
```

2021-11-18 20:11 UTC, alexandreaquiles commented on src/br/com/vaasschool/test/CategoryHtmlPageGenerator.java
> +                ps.println("<td>" + c.getOrder() + "<td>");
No card, não estava falando pra mostrar o código nem a ordem.

```suggestion
```

2021-11-18 20:11 UTC, alexandreaquiles commented on src/br/com/vaasschool/test/CategoryHtmlPageGenerator.java
> +            ps.println("<html>");
Faltou colocar o algumas coisas descritas no card:

- O número total de cursos da categoria
- A soma do total de horas estimadas dos cursos da categoria

2021-11-18 20:11 UTC, alexandreaquiles commented on src/br/com/vaasschool/test/CategoryHtmlPageGenerator.java
> +                for (Subcategory sub : c.getSubCategoryList()) {
No card, a lista de subcategorias deve ser ordenada pelo campo `ordem` e devem ser mostradas apenas as subcategorias ativas. 

> - Escrever no HTML, ordenadas pelo campo de `ordem`, as seguintes informações das subcategorias ativas:

2021-11-18 20:11 UTC, alexandreaquiles commented on src/br/com/vaasschool/reader/CourseReader.java
> +    private Course courseStructure(String[] vectorCourse) {
Pra manter o padrão do `SubcategoryReader`, acho que seria legal chamar esse método de `read` e o parâmetro de `courseData`.

2021-11-18 20:11 UTC, alexandreaquiles commented on src/br/com/vaasschool/model/CourseVisibility.java
> +                .orElseThrow(() -> new IllegalArgumentException("Visibilidade não encontrada"));
Reimplementa esse trecho sem Java 8, pra treinar!

2021-11-23 19:20 UTC, alexandreaquiles approved these changes

2021-11-23 19:20 UTC, merged