testes automatizados, script e modelagem do banco de dados
analuijesus/vaasschool pull request #3
Opened 2021-12-08 17:41 UTC by analuijesus

2021-12-09 19:14 UTC, mariasantosdev requested changes

2021-12-09 19:14 UTC, mariasantosdev commented on vaasschool.sql
> +  `active` bit(1),
Poderiamos por um valor default para essa coluna aqui também né?? 
Lembro que deixamos o default no java como false

2021-12-09 19:14 UTC, mariasantosdev commented on vaasschool.sql
> +  `active` bit(1),
Vale esse mesmo comentário para as outras colunas `active` de outras tabelas

2021-12-09 19:20 UTC, mariasantosdev commented
Muito bom o nome dos testes parabéns Ana!! Eu acabei colocando "Request changes" sem querer :p mas não precisa fazer todas as alterações que sugeri.
Se sobrar um tempo e quiser fazer um plus poderia fazer testes para a classe `Validator ` também :eyes:

2021-12-09 19:27 UTC, alexandreaquiles approved these changes
Muito bom!

2021-12-09 19:27 UTC, alexandreaquiles commented on vaasschool.sql
> +  `active` bit(1),
Boa, pq senão vai ser `null`.

2021-12-09 19:27 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/model/Course.java
> +
Está usando todos esses getters?

2021-12-09 19:30 UTC, mariasantosdev commented on vaasschool.sql
> +  `order` int not null,
O melhor seria não usar palavras reservadas..,fica um pouco ruim de trabalhar(sentimos isso na pele :laughing: )

2021-12-09 19:37 UTC, analuijesus commented on src/main/java/br/com/vaasschool/test/ScriptDataLoad.java
> +public class ScriptDataLoad {
real, vou aproveitar e deixar junto com a classe que cria o .html

2021-12-09 20:06 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/test/ScriptDataLoad.java
> +public class ScriptDataLoad {
Acho que o nome poderia ser melhor.....que tal `SqldataLoadGenerator` para ficar mais claro que essa classe gera scripts sql, oque acha?

2021-12-09 20:17 UTC, hopesoh commented on src/main/java/br/com/vaasschool/test/ScriptDataLoad.java
> +public class ScriptDataLoad {
eu tiraria a palavra load. :P Só deixaria SqlDataGenerator pra dizer que só gera, mesmo

2021-12-09 20:39 UTC, analuijesus commented on src/main/java/br/com/vaasschool/model/Course.java
> +
sim :)

2021-12-09 20:45 UTC, mariasantosdev commented on src/main/java/br/com/vaasschool/test/ScriptDataLoad.java
> +public class ScriptDataLoad {
Boa @hopesoh para mim faz sentido!!

2021-12-10 16:38 UTC, hopesoh approved these changes

2021-12-13 13:09 UTC, mariasantosdev approved these changes

2021-12-13 13:19 UTC, merged